name: Build geoip.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y_%m_%d_%H_%M)" >> $GITHUB_ENV
        shell: bash
      - name: Get GeoLite2-City
        env:
          ACCOUNT_ID: ${{ secrets.MAXMIND_ACCOUNT }}
          LICENSE_KEY: ${{ secrets.MAXMIND_LICEHSE }}
        run: |
          curl -L -u "${ACCOUNT_ID}:${LICENSE_KEY}" "https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz" -o GeoLite2-City.tar.gz
          tar zxvf ./GeoLite2-City.tar.gz -C .
          mkdir dist
          mv ./GeoLite2-City*/GeoLite2-City.mmdb ./dist/GeoLite2-City.mmdb
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/GeoLite2-City.mmdb
          tag_name: ${{ env.TAG_NAME }}
