name: Build geoip.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get GeoLite2
        env:
          LICENSE_KEY: ${{ secrets.MAXMIND_LICEHSE }}
        run: |
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${LICENSE_KEY}&suffix=tar.gz" -o GeoLite2-City.tar.gz
          tar zxvf ./GeoLite2-City.tar.gz -C .
          mkdir dist
          ls

